/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.socialize.titanium;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.proxy.TiViewProxy;

import android.app.Activity;

import com.socialize.ui.SocializeUI;

@Kroll.module(name="Socialize", id="com.socialize")
public class SocializeModule extends KrollModule
{
	public SocializeModule(TiContext tiContext) {
		super(tiContext);
	}
	
	@Kroll.method
	public SocializeActionBarViewProxy showActionBar(TiViewProxy parent, String entityKey) {
		return new SocializeActionBarViewProxy(getTiContext(), parent, entityKey);
	}
	
	@Override
	public void onDestroy(Activity activity) {
		SocializeUI.getInstance().destroy(activity);
		super.onDestroy(activity);
	}

	@Kroll.method
	public void setSocializeCredentials(String consumerKey, String consumerSecret) {
		SocializeUI.getInstance().setSocializeCredentials(consumerKey, consumerSecret);
	}
	
	@Kroll.method
	public void setFacebookAppId(String appId) {
		SocializeUI.getInstance().setFacebookAppId(appId);
	}
}
