Entities stored in Socialize can optionally include *meta data*.  This is for any additional information you want to store about the entity.

Meta data is stored with the entity and returned then the entity is requested.

.. literalinclude:: ../../../../demo/src/com/socialize/demo/snippets/EntitySnippets.java
	:start-after: begin-snippet-6
	:end-before: end-snippet-6

If you want a more complex data structure, we recommend using JSON as an object notation

.. literalinclude:: ../../../../demo/src/com/socialize/demo/snippets/EntitySnippets.java
	:start-after: begin-snippet-7
	:end-before: end-snippet-7